Capstone/Models/DonationItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Capstone.Models
{
    public class DonationItem
    {
        [Key]
        public int ItemId { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string ItemName { get; set; }

        [Required]
        [Display(Name = "Quantity")]
        public int ItemQuantity { get; set; }

        [Display(Name = "Size")]
        public string ItemSize { get; set; }

        [Required]
        [ForeignKey("Category")]
        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        public ItemCategory Category { get; set; }

        public string Brand { get; set; }

        public string Color { get; set; }

        [Display(Name = "Description")]
        public string ItemDescription { get; set; }

        [NotMapped]
        [DataType(DataType.Upload)]
        public HttpPostedFileBase ImageUpload { get; set; }

        public string ImageFilePath { get; set; }

        [ForeignKey("Organization")]
        public int RequestingOrganizationId { get; set; }
        public NonprofitOrganization Organization { get; set; }


    }
}

Capstone/Controllers/CartItemsController.cs
using Capstone.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.Controllers
{
    public class CartItemsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: CartItems
        public ActionResult Index()
        {
            return View();
        }

        // GET: CartItems/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

      
        public ActionResult Create(int donationItemId, int supporterId, int quantity)
        {
            var donationItem = db.DonationItem.Where(c => c.ItemId == donationItemId).First();

            CartItem item = new CartItem()
            {
                SupporterId = supporterId,
                Supporter = db.Supporters.Where(c => c.SupporterId == supporterId).First(),
                DateCreated = System.DateTime.Today,
                ProductId = donationItem.ItemId,
                Product = donationItem,
                Quantity = quantity
            };

            db.CartItem.Add(item);
            db.SaveChanges();

            return RedirectToAction("AddToBasket", "DonationBaskets", item);
        }


        // GET: CartItems/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CartItems/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CartItems/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CartItems/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Capstone/Controllers/DonationItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capstone.Models;
using Capstone.ViewModels;
using Microsoft.AspNet.Identity;

namespace Capstone.Controllers
{
    public class DonationItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: DonationItems
        public ActionResult Index(int organizationId, int? categoryId, int? supporterId)
        {
            var organization = db.NonprofitOrganizations.Find(organizationId);
            string role = null;
            if (supporterId == null)
            {
                var userId = User.Identity.GetUserId();
                try
                {
                    supporterId = db.Supporters.Where(c => c.UserId == userId).First().SupporterId;
                    role = "Supporter";
                }
                catch
                {
                    supporterId = null;
                    role = "Organization";
                }
            }

            OrgRequestItemsListViewModel viewModel = new OrgRequestItemsListViewModel()
            {
                SupporterId = supporterId,
                OrganizationId = organizationId,
                OrganizationDescription = organization.OrganizationDescription,
                OrganizationName = organization.OrganizationName,
                UserRole = role
            };
            if(categoryId != null)
            {
                viewModel.ItemsList = db.DonationItem.Include(d => d.Category).Where(c => c.RequestingOrganizationId == organization.OrganizationId && c.CategoryId == categoryId);
            }
            if(categoryId == null || categoryId == 0)
            {

                viewModel.ItemsList = db.DonationItem.Include(d => d.Category).Where(c => c.RequestingOrganizationId == organization.OrganizationId);
            }
            ViewBag.Categories = db.ItemCategories.Distinct();

            var list = new List<SelectListItem>();
            for (var i = 1; i < 51; i++)
                list.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });
            ViewBag.QuantityList = list;

            return View(viewModel);
        }

        // GET: DonationItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonationItem donationItem = db.DonationItem.Find(id);
            ViewBag.CategoryName = db.ItemCategories.Find(donationItem.CategoryId).Name;
            if (donationItem == null)
            {
                return HttpNotFound();
            }
            return View(donationItem);
        }

        // GET: DonationItems/Create
        public ActionResult Create(int organizationId)
        {
            DonationItemCreateViewModel viewModel = new DonationItemCreateViewModel()
            {
                OrganizationId = organizationId,
                Organization = db.NonprofitOrganizations.Where(c => c.OrganizationId == organizationId).First(),
                //Categories = db.ItemCategories.Distinct().ToList()
            };
            ViewBag.CategoryId = new SelectList(db.ItemCategories, "CategoryId", "Name", viewModel.CategoryId);

            return View(viewModel);
        }

        // POST: DonationItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemId,ItemName,ItemQuantity,ItemSize,CategoryId,Brand,Color,ItemDescription,OrganizationId,Organization,ImageUpload")] DonationItemCreateViewModel vm)
        {
            if (ModelState.IsValid)
            {
                DonationItem item = new DonationItem()
                {
                    ItemName = vm.ItemName,
                    ItemQuantity = vm.ItemQuantity,
                    ItemSize = vm.ItemSize,
                    CategoryId = vm.CategoryId,
                    Category = db.ItemCategories.Where(c => c.CategoryId == vm.CategoryId).First(),
                    Brand = vm.Brand,
                    Color = vm.Color,
                    ItemDescription = vm.ItemDescription,
                    RequestingOrganizationId = vm.OrganizationId,
                    Organization = vm.Organization
                };

                if (vm.ImageUpload != null && vm.ImageUpload.ContentLength > 0)
                {
                    var uploadDir = "~/Content/ImageUploads";
                    var imagePath = Path.Combine(Server.MapPath("~/Content/ImageUploads"), vm.ImageUpload.FileName);
                    var imageUrl = Path.Combine(uploadDir, vm.ImageUpload.FileName);
                    vm.ImageUpload.SaveAs(imagePath);
                    item.ImageFilePath = imageUrl;
                }


                db.DonationItem.Add(item);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = item.ItemId });
            }

            
            return View(vm);
        }

        // GET: DonationItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonationItem donationItem = db.DonationItem.Find(id);
            if (donationItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.ItemCategories, "CategoryId", "Name", donationItem.CategoryId);
            return View(donationItem);
        }

        // POST: DonationItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemId,ItemName,ItemQuantity,ItemSize,CategoryId,Brand,Color,ItemDescription,OrganizationId,Organization,ImageUpload")] DonationItem donationItem)
        {
            if (ModelState.IsValid)
            {
                if (donationItem.ImageUpload != null && donationItem.ImageUpload.ContentLength > 0)
                {
                    var uploadDir = "~/Content/ImageUploads";
                    var imagePath = Path.Combine(Server.MapPath("~/Content/ImageUploads"), donationItem.ImageUpload.FileName);
                    var imageUrl = Path.Combine(uploadDir, donationItem.ImageUpload.FileName);
                    donationItem.ImageUpload.SaveAs(imagePath);
                    donationItem.ImageFilePath = imageUrl;
                }

                db.Entry(donationItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.ItemCategories, "CategoryId", "Name", donationItem.CategoryId);
            return View(donationItem);
        }

        // GET: DonationItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonationItem donationItem = db.DonationItem.Find(id);
            if (donationItem == null)
            {
                return HttpNotFound();
            }
            return View(donationItem);
        }

        // POST: DonationItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DonationItem donationItem = db.DonationItem.Find(id);
            db.DonationItem.Remove(donationItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Capstone/Views/DonationItems/Create.cshtml
@model Capstone.ViewModels.DonationItemCreateViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Donation Request</h2>

<form action="" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
<div class="form-horizontal">
    <h4>Donation Item</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ItemName, "Item Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="small text-danger">
            *Required
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ItemQuantity, "Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="small text-danger">
            *Required
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ItemQuantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ItemQuantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ItemSize, "Size", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ItemSize, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ItemSize, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="small text-danger">
            *Required
        </div>
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ItemDescription, "Description", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.ImageUpload, "Example Image", htmlAttributes: new { @class = "control-label col-md-2" })
        
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ImageUpload, new { type = "file" })
        </div>
            @*<div class="col-md-offset-2 col-md-10">
                <input type="file" name="ImageData" id="ImageData" value="Upload" class="btn btn-primary" />
            </div>*@
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 text-success">
            @ViewBag.FileStatus
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Capstone/Views/DonationItems/Delete.cshtml
@model Capstone.Models.DonationItem

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DonationItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemQuantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemQuantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestingOrganizationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestingOrganizationId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MyProperty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MyProperty)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Capstone/Views/DonationItems/Details.cshtml
@model Capstone.Models.DonationItem

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h4>Donation Item Details</h4>
    <hr />
    <dl class="col-md-6">

        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemName)
        </dd>

        @if (Model.ItemQuantity != 0)
        {
            <dt>
                Quantity
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ItemQuantity)
            </dd>
        }


        <dt>
            Category
        </dt>

        <dd>
            @ViewBag.CategoryName
        </dd>

        @if (Model.ItemSize != null)
        {
            <dt>
                Size
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ItemSize)
            </dd>
        }


        @if (Model.ItemDescription != null)
        {
            <dt>
                Description
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ItemDescription)
            </dd>
        }


        @*<dt>
            @Html.DisplayNameFor(model => model.RequestingOrganizationId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestingOrganizationId)
        </dd>*@

        @*<dt>
            @Html.DisplayNameFor(model => model.MyProperty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MyProperty)
        </dd>*@

    </dl>
    <dl class="col-md-6">
        @if (Model.ImageFilePath != null)
        {
            @*<dt>
                @Html.DisplayNameFor(model => model.ImageFilePath)
            </dt>*@

            <dd>
                <div class="img-fluid">
                    <img src=@Url.Content(Model.ImageFilePath) style="overflow: hidden; position: relative; width:200px;" />
                </div>
            </dd>
        }
    </dl>

   
</div>
    @if (User.IsInRole("Organization"))
    {
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ItemId }) |
        @Html.ActionLink("Back to List", "Index", new { organizationId = Model.RequestingOrganizationId }) |
        @Html.ActionLink("Add Another Item", "Create", "DonationItems", new { organizationId = Model.RequestingOrganizationId }, null)

    </p>
    }
    @if (!User.IsInRole("Organization"))
    {
        @Html.ActionLink("Back to List", "Index", new { organizationId = Model.RequestingOrganizationId})
    }

Capstone/Views/DonationItems/Edit.cshtml
@model Capstone.Models.DonationItem

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<form action="" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal">
        <h4>DonationItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ItemId)

        <div class="form-group">
            @Html.LabelFor(model => model.ItemName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="small text-danger">
                *Required
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="small text-danger">
                *Required
            </div>
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUpload, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageUpload, new { type = "file" })
            </div>
            <br />
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
        </div>
    </form>

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

Capstone/Views/DonationItems/Index.cshtml
@model Capstone.ViewModels.OrgRequestItemsListViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">@Model.OrganizationName</h1>
<hr />
<h6 class="text-center">@Model.OrganizationDescription</h6>
<hr />

@using (Html.BeginForm())
{
<div>
    @Html.Hidden("organizationId", Model.OrganizationId)
    Category: @Html.DropDownList("categoryId", new SelectList(ViewBag.Categories, "CategoryId", "Name"), "All", null)
    <input type="submit" value="Search" class="btn-primary" />
</div>
}

@if (User.IsInRole("Organization"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Size
        </th>
        <th>
            Color
        </th>
        <th>
            Quantity Needed
        </th>
        <th>
            Category
        </th>
        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model.ItemsList)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemSize)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemQuantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>

        @if (Model.UserRole == "Organization")
        {
            <td></td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ItemId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ItemId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ItemId })
            </td>
        }
        @if (Model.UserRole == "Supporter")
        {

            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ItemId })
            </td>
            <td>

                @using (Html.BeginForm("Create", "CartItems", new { enctype = "multipart/form-data" }))
                {
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div>
                    @Html.Hidden("donationItemId", item.ItemId)
                    @Html.Hidden("supporterId", Model.SupporterId)
                    Quantity: @Html.DropDownList("quantity", new SelectList(ViewBag.QuantityList, "Text", "Value"), " ", null)
                    @Html.ValidationMessage("quantity", "", new { @class = "text-danger" })
                    <input type="submit" value="Add To Basket" />
                </div>
                }
            </td>
        }


    </tr>
    }

</table>